apiVersion: v1
kind: Secret
metadata:
  name: chatmern-secrets
type: Opaque
stringData:
  MONGO_DB_URI: mongodb://mongo:27017/chatmern
  JWT_SECRET: replace-me
  AWS_REGION: ap-south-1
  AWS_S3_BUCKET: your-chat-attachments
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
